### ISSUE TITLE
Error: woocommerce_rest_product_not_created

### ISSUE THREAD

**Issue by Sturzaker123** [woothemes/wc-api-php#352] opened 2024-09-16 05:37 UTC
["message"]=>
        string(87) "The SKU (UNDER COATING GUN) you are trying to insert is already under processing"

I am getting multiple items saying they are under processing when I try and create them, however I search the sku in the products I cannot find them, 

I have even downloaded my database and tried to search the SKU and I cannot find it,

So what exactly does "already under processing" mean?

Below is the request I am sending.

```
[create] => Array
                (
                    [0] => Array
                        (
                            [name] => Puma 1/4" Filter & Regulator
                            [type] => simple
                            [description] => Puma 1/4" Filter & Regulator<br /><br />
<br /><br />
Puma – ‘Air Center’.<br /><br />
<br /><br />
Buy with confidence, operating since 1979, sold in over 136 countries, Puma is a world leader in manufacturing PROFESSIONAL Air Tools!<br /><br />
<br /><br />
Buy professional Puma Air tools for reassurance of quality, safety and performance when it really counts!<br /><br />
<br /><br />
Range of pressure: 0.5-9.9kg/cm<br /><br />
Max. pressure: 150psi<br /><br />
Max.mm flow rate: 1000 L/min<br /><br />
Operating temperature: 5 - 60deg<br /><br />
Max. temperature: 80deg<br /><br />
Port size: 1/4"<br /><br />
Filter screen micron: 40m<br /><br />
Model: 1/4" Filter Regulator<br /><br />
<br /><br />
Warranty:<br /><br />
Puma offers a 12 MONTH WARRANTY back to base manufacturers warranty. See our stores page for terms. (Misuse, consumables and fair wear and tear excluded.)<br /><br />
<br /><br />
<br /><br />
<br /><br />
<br /><br />
100% New Zealand Owned & Operated<br /><br />
Quality Products<br /><br />
Professional Customer Service & Support!<br /><br />
GST Receipt Emailed with Every Purchase<br /><br />
Price Matching<br /><br />
<br /><br />
Free Shipping to non rural addresses or collect from freight depot. <br /><br />
<br /><br />
<br /><br />
Kws: petrol tyre air compressor, air tool, compressor air, paint spray gun, compressor pump, hose, spray painting equipment<hr /><br />
<em>This product has <strong>Free Shipping</strong> - <a href="/about-us/shipping/">More Information</a></em><br />
<em>This product <strong>cannot be picked up</strong> - <a href="/faq/pick-up/">More information</a></em>
                            [short_description] => Range of pressure: 0.5-9.9kg/cm<br />
Max. pressure: 150 psi<br />
Max. mm flow rate: 1000 L/min<br />
Operating temperature: 5 - 60C<br />
Max. temperature: 80C<br />
Port size: 1/4“<br />
Filter screen micron: 40µm
                            [sku] => 1/4" FILTER  REGULAT
                            [manage_stock] => 1
                            [stock_quantity] => 8
                            [weight] => 0
                            [dimensions] => Array
                                (
                                    [length] => 0
                                    [width] => 0
                                    [height] => 0
                                )

                            [categories] => Array
                                (
                                    [0] => Array
                                        (
                                            [id] => 15
                                        )

                                )

                            [tags] => Array
                                (
                                )

                            [shipping_class] => 
                            [status] => publish
                            [sale_price] => 126.95
                            [regular_price] => 126.95
                            [price] => 
                            [date_on_sale_from] => 0
                            [date_on_sale_to] => 0
                        )

```

**Comment by naman03malhotra** [comment] 2024-09-20 11:49
Closing as duplicate of https://github.com/woocommerce/woocommerce/issues/51412

**Closed as completed by naman03malhotra** 2024-09-20 11:49 UTC
